# This is a generated file. Not intended for manual editing.
services:
  catalog-api:
    build:
      context: "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src"
      dockerfile: "Services/Catalog/CatalogAPI/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57402"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "catalogapi:dev"
    ports:
    - "127.0.0.1:57002:57000"
    - "127.0.0.1:57202:57200"
    - "127.0.0.1:57402:57402"
    volumes:
    - "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src/Services/Catalog/CatalogAPI:/app:rw"
    - "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src:/src:rw"
    - "/home/ikaro-lisarb/.nuget/packages:/home/app/.nuget/packages"
    - "/home/ikaro-lisarb/.local/share/JetBrains/RiderRemoteDebugger/2025.2.1/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/628/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/ikaro-lisarb/.cache/JetBrains/Rider2025.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_9_13_18_21_26:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
