# This is a generated file. Not intended for manual editing.
services:
  basket-api:
    build:
      context: "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57403"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "basket-api:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57403"
    volumes:
    - "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src/Services/Basket/Basket.API:/app:rw"
    - "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src:/src:rw"
    - "/home/ikaro-lisarb/.nuget/packages:/home/app/.nuget/packages"
    - "/home/ikaro-lisarb/.local/share/JetBrains/RiderRemoteDebugger/2025.2.1/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/628/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/ikaro-lisarb/.cache/JetBrains/Rider2025.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_9_16_13_06_59:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  catalog-api:
    build:
      context: "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src"
      dockerfile: "Services/Catalog/CatalogAPI/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57404"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "catalogapi:dev"
    ports:
    - "127.0.0.1:57004:57000"
    - "127.0.0.1:57204:57200"
    - "127.0.0.1:57404:57404"
    volumes:
    - "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src/Services/Catalog/CatalogAPI:/app:rw"
    - "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src:/src:rw"
    - "/home/ikaro-lisarb/.nuget/packages:/home/app/.nuget/packages"
    - "/home/ikaro-lisarb/.local/share/JetBrains/RiderRemoteDebugger/2025.2.1/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/628/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/ikaro-lisarb/.cache/JetBrains/Rider2025.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_9_16_13_06_59:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  discount-grpc:
    build:
      context: "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src"
      dockerfile: "Services/Discount/Discount.GRPC/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57405"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "discount-grpc:dev"
    ports:
    - "127.0.0.1:57005:57000"
    - "127.0.0.1:57205:57200"
    - "127.0.0.1:57405:57405"
    volumes:
    - "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src/Services/Discount/Discount.GRPC:/app-1:rw"
    - "/home/ikaro-lisarb/Desktop/projects/ms-course/EshopMS/src:/src:rw"
    - "/home/ikaro-lisarb/.nuget/packages:/home/app/.nuget/packages"
    - "/home/ikaro-lisarb/.local/share/JetBrains/RiderRemoteDebugger/2025.2.1/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/snap/rider/628/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/home/ikaro-lisarb/.cache/JetBrains/Rider2025.2/log/DebuggerWorker/JetBrains.Debugger.Worker.2025_9_16_13_06_59:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app-1"
