services:
  catalog-db:
    image: postgres
    container_name: catalog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - catalog-db-data:/var/lib/postgresql/data
  
  basket-db:
    image: postgres
    container_name: basket-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - basket-db-data:/var/lib/postgresql/data
  
  ordering-db:
    image: mcr.microsoft.com/mssql/server
    container_name: ordering-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Swn12345678
      - MSSQL_PID=Developer
    restart: always
    ports:
      - "1433:1433"

  distributed-cache:
    image: redis
    container_name: distributed-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  message-broker:
    image: rabbitmq:management
    container_name: message-broker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  
  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Host=catalog-db;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
    ports:
      - "6000:8080"
    depends_on:
      - catalog-db
  
  basket-api:
    image: basket-api
    container_name: basket-api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Host=basket-db;Port=5432;Database=BasketDb;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=distributed-cache:6379
      - GRPC__DiscountUrl=http://discount-grpc:8080
      - MessageBroker__Host=amqp://ecommerce-mq:5672

    ports:
      - "6001:8080"
    depends_on:
      - basket-db
      - distributed-cache
      - discount-grpc
      - message-broker
  
  discount-grpc:
    image: discount-grpc
    container_name: discount-grpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Data Source=/app/discount-db.sqlite
    ports:
      - "6002:8080"
    volumes:
      - discount-db-data:/app


volumes:
  catalog-db-data:
  basket-db-data:
  redis-data:
  discount-db-data:
  

