services:
  catalog-db:
    image: postgres
    container_name: catalog-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - catalog-db-data:/var/lib/postgresql/data
  
  basket-db:
    image: postgres
    container_name: basket-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - basket-db-data:/var/lib/postgresql/data
  
  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Host=catalog-db;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
    ports:
      - "6000:8080"
    depends_on:
      - catalog-db

volumes:
  catalog-db-data:
  basket-db-data:
    