services:
  catalog-db:
    image: postgres:latest
    container_name: catalog_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=53fa7365acf8ec19be2356b03ad00c4f
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - catalog_db:/var/lib/postgresql/data
volumes:
  catalog_db:
